[build]
builder = "nixpacks"

[[services]]
name = "client"
root_directory = "client"
[services.deploy]
build_command = "npm install && npm run build"
start_command = "npx serve -s dist -p $PORT"

[[services]]  
name = "server"
root_directory = "server"
[services.deploy]
start_command = "npm run migrate && npm start"